### ISSUE TITLE
Error when importing

### ISSUE THREAD

**Issue by zakcutner** [angel-dart/diagnostics#10]
I have included `angel_diagnostics` in my `pubspec.yaml` file like so: `angel_diagnostics: ^1.0.2`.

However when I attempt to `import 'package:angel_diagnostics/angel_diagnostics.dart';` in my dart file, I get the following error:

```
Unable to spawn isolate: 'package:angel_diagnostics/src/log_requests.dart': malformed type: line 12 pos 30: cannot resolve class 'AngelPlugin' from '_RequestLogger@39222342'
class _RequestLogger extends AngelPlugin {
```

Would someone be able to help me understand what the issue is please?

**Comment by thosakwe** [comment]
`package:angel_diagnostics` is completely deprecated as of Angel `>=1.1.0-alpha`.

Check out the migration guide for any further concerns:
https://angel-dart.gitbook.io/angel/1.1.0-migration-guide

I'm going to go ahead and mark this repo as deprecated; thanks for bringing it to my attention.
